site_name: Documentação RioSaúde
site_author: Inteligência de Negócios da RioSaúde
copyright: >
  © 2024 | Desenvolvido pela Inteligência de Negócios da RioSaúde | Versão v1.0.0
  <p>Onde Estamos:</p>
      <div class="social-links-home">
        <a href="https://www.linkedin.com/company/riosaudeoficial/posts/?feedView=all" target="_blank">
          <img src="https://img.icons8.com/?size=100&id=13930&format=png&color=000000" alt="Instagram">
        </a>
        <a href="https://mobile.twitter.com/riosaudeoficial" target="_blank">
          <img src="https://img.icons8.com/?size=100&id=yoQabS8l0qpr&format=png&color=000000" alt="Twitter">
        </a>
        <a href="https://www.instagram.com/riosaudeoficial/" target="_blank">
          <img src="https://img.icons8.com/?size=100&id=Xy10Jcu1L2Su&format=png&color=000000" alt="Instagram">
        </a>
      </div>
  <p>Rua Dona Mariana, 48 - Botafogo, Rio de Janeiro - RJ, 22280-020</p>

nav:
  - Página Inicial: index.md
  - Projetos:
    - Consolidado CNES:
      - Documentação: consolidado_cnes/documentacao_consolidado_cnes.md
      - Versionamento: consolidado_cnes/versao_consolidado_cnes.md
    - Performance das Unidades:
      - Documentação: irs_gerencial/documentacao_irs_gerencial.md
      - Regras de Negócios: irs_gerencial/regras_negocio_irs_gerencial.md
      - Esquemas: irs_gerencial/esquema_irs_gerencial.md
      - Versionamento: irs_gerencial/versao_irs_gerencial.md
  - Sobre Nós: about.md

extra_css:
  - css/extra.css
  - css/custom.css


use_directory_urls: true
extra:
  src_dir: src

theme:
  name: material
  language: pt-BR
  logo: src/logo-riosaude-horizontal-monocromatico.png
  hide:
    - navigation
    - toc

plugins:
  - mermaid2
  - mkdocstrings

repo_url: https://github.com/jeantorre/riosaude_documentacao
